[browser]
serverAddress = '0.0.0.0'

[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'
# "#6eb52f"
# '#7792E3'

# Background color for the main content area
backgroundColor = '#fff8ec'
# '#fff8ec'
# "#f0f0f5" - white
# '#A1A1A1'
# "#606062"
# "#f0f0f5"
# '#273346'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#e9ae61'
# '#8e008e'
# '#cd00cd'
# '#73116e'
# '#4b0b48' - deep purple
# '#dcdcf5'
# "#586e75"
# "#A901DB"
# "#e0e0ef"
# "#586e75"

# Color used for almost all text
textColor = "#261a48"
# '#362e53'
# "#262730"
# "#fafafa"
# '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"